// Global, cross-user cache of generated OR Prep content, keyed on normalized case
// description text. One row per distinct description — once a procedure (especially a
// Home-screen chip's fullName) has been generated once by anyone, every matching request
// after that is served from Parse instead of calling OpenAI again. Unlike `ScrubCase`
// (cloud/scrubPrep/cases.js), this is not scoped to an owner: it exists purely to cut
// redundant OpenAI spend, not to track what any particular user has saved.
//
// A cache entry is tied to PROMPT_VERSION: bump that constant whenever prep.js's prompt
// changes meaningfully, and existing entries are treated as misses (regenerated and
// overwritten in place) instead of silently serving content generated by an old prompt
// forever.

const PROMPT_VERSION = 1;

// Case/whitespace-insensitive: collapses internal runs of whitespace too (not just
// leading/trailing), so e.g. "Lap  Chole" and "lap chole" share a cache entry.
function normalizeDescription(text) {
  return (text || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ");
}

async function fetchCatalogObject(normalizedDescription) {
  const query = new Parse.Query("PrepCatalog");
  query.equalTo("normalizedDescription", normalizedDescription);
  return query.first({ useMasterKey: true });
}

/**
 * @param {string} normalizedDescription
 * @param {{ fetchCatalogObject?: typeof fetchCatalogObject }} [deps]
 * @returns {Promise<object|null>} the cached prep JSON, or null on a miss — not found, or
 *   found but written by an older prompt version (treated the same as not found).
 */
async function getCachedPrep(normalizedDescription, deps = {}) {
  const fetch = deps.fetchCatalogObject || fetchCatalogObject;
  const existing = await fetch(normalizedDescription);
  if (!existing) return null;
  if (existing.get("promptVersion") !== PROMPT_VERSION) return null;
  return existing.get("prep");
}

function newCatalogObject() {
  const PrepCatalogClass = Parse.Object.extend("PrepCatalog");
  return new PrepCatalogClass();
}

/**
 * Inserts the catalog entry for `normalizedDescription`, or overwrites it in place if one
 * already exists (e.g. a stale prompt-version row) rather than accumulating duplicates.
 *
 * @param {{ caseDescription: string, normalizedDescription: string, prep: object }} params
 * @param {{ fetchCatalogObject?: typeof fetchCatalogObject, newCatalogObject?: typeof newCatalogObject }} [deps]
 */
async function upsertCatalogEntry({ caseDescription, normalizedDescription, prep }, deps = {}) {
  const fetch = deps.fetchCatalogObject || fetchCatalogObject;
  const createNew = deps.newCatalogObject || newCatalogObject;
  const existing = await fetch(normalizedDescription);
  const entry = existing || createNew();
  entry.set("caseDescription", caseDescription);
  entry.set("normalizedDescription", normalizedDescription);
  entry.set("prep", prep);
  entry.set("promptVersion", PROMPT_VERSION);
  await entry.save(null, { useMasterKey: true });
  return entry;
}

module.exports = {
  PROMPT_VERSION,
  normalizeDescription,
  fetchCatalogObject,
  getCachedPrep,
  newCatalogObject,
  upsertCatalogEntry,
};
