import SwiftUI

/// Every Learn source in one place, grouped by screen — reachable from the Learn tab and
/// from the AI-content note on case prep screens.
struct LearnSourcesView: View {
    var body: some View {
        List {
            Section {
                Text("Learn content is written for medical students and reviewed by a surgeon. Case preparations, Quiz Me, and Rapid Fire are generated by AI for study — check them against these references and your clinical team.")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
            }

            ForEach(LearnSources.all, id: \.screen) { group in
                Section(group.screen) {
                    ForEach(group.sources) { source in
                        LearnSourceRow(source: source)
                    }
                }
            }

            Section {
                Text(LearnSources.reviewStatement)
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
        }
        .listStyle(.insetGrouped)
        .navigationTitle("Sources & References")
        .navigationBarTitleDisplayMode(.inline)
    }
}

#Preview {
    NavigationStack {
        LearnSourcesView()
    }
}
